// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

//go:build wasm
// +build wasm

package main

import "github.com/iotaledger/wasp/packages/wasmvm/wasmvmhost"

import "github.com/iotaledger/wasp/contracts/wasm/plantobelly/go/plantobelly"

func main() {
}

func init() {
	wasmvmhost.ConnectWasmHost()
}

//export on_call
func onCall(index int32) {
	plantobelly.OnLoad(index)
}

//export on_load
func onLoad() {
	plantobelly.OnLoad(-1)
}
