// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmtypes from "wasmlib/wasmtypes";

export const ScName        = "plantobelly";
export const ScDescription = "plantobelly smart contract responsible for handling plants";
export const HScName       = new wasmtypes.ScHname(0x1eaa52f2);

export const ParamActive          = "active";
export const ParamActiveReason    = "activeReason";
export const ParamAmount          = "amount";
export const ParamClaimID         = "claimID";
export const ParamClaimId         = "claimId";
export const ParamClaimed         = "claimed";
export const ParamCovered         = "covered";
export const ParamCurrentWater    = "currentWater";
export const ParamDescription     = "description";
export const ParamDuration        = "duration";
export const ParamFunds           = "funds";
export const ParamId              = "id";
export const ParamLattitude       = "lattitude";
export const ParamLocation        = "location";
export const ParamLongitude       = "longitude";
export const ParamManufacturer    = "manufacturer";
export const ParamName            = "name";
export const ParamNewPlant        = "newPlant";
export const ParamNewState        = "newState";
export const ParamOracleId        = "oracleId";
export const ParamOwner           = "owner";
export const ParamOwnerId         = "ownerId";
export const ParamPayReward       = "payReward";
export const ParamPlantId         = "plantId";
export const ParamReqOwnerId      = "reqOwnerId";
export const ParamReqPlantId      = "reqPlantId";
export const ParamReward          = "reward";
export const ParamTimeoutDuration = "timeoutDuration";
export const ParamTimestamp       = "timestamp";
export const ParamTo              = "to";
export const ParamValue           = "value";
export const ParamWaterLevel      = "waterLevel";
export const ParamWaterTarget     = "waterTarget";
export const ParamWaterThreshold  = "waterThreshold";

export const ResultClaim   = "claim";
export const ResultClaims  = "claims";
export const ResultIsOwner = "isOwner";
export const ResultOracles = "oracles";
export const ResultOwner   = "owner";
export const ResultPlant   = "plant";
export const ResultPlants  = "plants";

export const StateAllowedPlantOracles   = "allowedPlantOracles";
export const StateAllowedWeatherOracles = "allowedWeatherOracles";
export const StateClaimIds              = "claimIds";
export const StateClaims                = "claims";
export const StateOwnedPlants           = "ownedPlants";
export const StateOwner                 = "owner";
export const StatePlantIds              = "plantIds";
export const StatePlantOwners           = "plantOwners";
export const StatePlants                = "plants";

export const FuncActivatePlantOwner     = "activatePlantOwner";
export const FuncAddPlantFunds          = "addPlantFunds";
export const FuncAddPlantOracle         = "addPlantOracle";
export const FuncAddWeatherOracle       = "addWeatherOracle";
export const FuncClaimWatering          = "claimWatering";
export const FuncEditOwnPlant           = "editOwnPlant";
export const FuncInit                   = "init";
export const FuncInterruptWeatherEvent  = "interruptWeatherEvent";
export const FuncMintPlant              = "mintPlant";
export const FuncMintPlantRaw           = "mintPlantRaw";
export const FuncPayClaimer             = "payClaimer";
export const FuncResolveClaim           = "resolveClaim";
export const FuncSetOwner               = "setOwner";
export const FuncSetPlantWater          = "setPlantWater";
export const FuncSetPlantWeatherTimeout = "setPlantWeatherTimeout";
export const ViewGetClaim               = "getClaim";
export const ViewGetClaims              = "getClaims";
export const ViewGetOwner               = "getOwner";
export const ViewGetPlant               = "getPlant";
export const ViewGetPlantOracles        = "getPlantOracles";
export const ViewGetPlants              = "getPlants";
export const ViewGetPlantsFromOwner     = "getPlantsFromOwner";
export const ViewGetWeatherOracles      = "getWeatherOracles";
export const ViewIsPlantOwner           = "isPlantOwner";

export const HFuncActivatePlantOwner     = new wasmtypes.ScHname(0x666005c8);
export const HFuncAddPlantFunds          = new wasmtypes.ScHname(0xe756567a);
export const HFuncAddPlantOracle         = new wasmtypes.ScHname(0xca04a73a);
export const HFuncAddWeatherOracle       = new wasmtypes.ScHname(0x5f3b8b83);
export const HFuncClaimWatering          = new wasmtypes.ScHname(0x1c41f3ed);
export const HFuncEditOwnPlant           = new wasmtypes.ScHname(0xebba038d);
export const HFuncInit                   = new wasmtypes.ScHname(0x1f44d644);
export const HFuncInterruptWeatherEvent  = new wasmtypes.ScHname(0xc42865d1);
export const HFuncMintPlant              = new wasmtypes.ScHname(0x6aeb84a1);
export const HFuncMintPlantRaw           = new wasmtypes.ScHname(0x7b8d3bec);
export const HFuncPayClaimer             = new wasmtypes.ScHname(0x2c37ad88);
export const HFuncResolveClaim           = new wasmtypes.ScHname(0x302e03fa);
export const HFuncSetOwner               = new wasmtypes.ScHname(0x2a15fe7b);
export const HFuncSetPlantWater          = new wasmtypes.ScHname(0x6a4d53e6);
export const HFuncSetPlantWeatherTimeout = new wasmtypes.ScHname(0x6f912118);
export const HViewGetClaim               = new wasmtypes.ScHname(0x80ab4e34);
export const HViewGetClaims              = new wasmtypes.ScHname(0xb307c3ab);
export const HViewGetOwner               = new wasmtypes.ScHname(0x137107a6);
export const HViewGetPlant               = new wasmtypes.ScHname(0x356278e0);
export const HViewGetPlantOracles        = new wasmtypes.ScHname(0xf1939bee);
export const HViewGetPlants              = new wasmtypes.ScHname(0x39ab8724);
export const HViewGetPlantsFromOwner     = new wasmtypes.ScHname(0x1e36cb62);
export const HViewGetWeatherOracles      = new wasmtypes.ScHname(0x66e143a7);
export const HViewIsPlantOwner           = new wasmtypes.ScHname(0x84c4d3ec);
