// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";
import * as sc from "./index";

export const IdxParamActive          = 0;
export const IdxParamActiveReason    = 1;
export const IdxParamAmount          = 2;
export const IdxParamClaimID         = 3;
export const IdxParamClaimId         = 4;
export const IdxParamClaimed         = 5;
export const IdxParamCovered         = 6;
export const IdxParamCurrentWater    = 7;
export const IdxParamDescription     = 8;
export const IdxParamDuration        = 9;
export const IdxParamFunds           = 10;
export const IdxParamId              = 11;
export const IdxParamLattitude       = 12;
export const IdxParamLocation        = 13;
export const IdxParamLongitude       = 14;
export const IdxParamManufacturer    = 15;
export const IdxParamName            = 16;
export const IdxParamNewPlant        = 17;
export const IdxParamNewState        = 18;
export const IdxParamOracleId        = 19;
export const IdxParamOwner           = 20;
export const IdxParamOwnerId         = 21;
export const IdxParamPayReward       = 22;
export const IdxParamPlantId         = 23;
export const IdxParamReqOwnerId      = 24;
export const IdxParamReqPlantId      = 25;
export const IdxParamReward          = 26;
export const IdxParamTimeoutDuration = 27;
export const IdxParamTimestamp       = 28;
export const IdxParamTo              = 29;
export const IdxParamValue           = 30;
export const IdxParamWaterLevel      = 31;
export const IdxParamWaterTarget     = 32;
export const IdxParamWaterThreshold  = 33;

export const IdxResultClaim   = 34;
export const IdxResultClaims  = 35;
export const IdxResultIsOwner = 36;
export const IdxResultOracles = 37;
export const IdxResultOwner   = 38;
export const IdxResultPlant   = 39;
export const IdxResultPlants  = 40;

export const IdxStateAllowedPlantOracles   = 41;
export const IdxStateAllowedWeatherOracles = 42;
export const IdxStateClaimIds              = 43;
export const IdxStateClaims                = 44;
export const IdxStateOwnedPlants           = 45;
export const IdxStateOwner                 = 46;
export const IdxStatePlantIds              = 47;
export const IdxStatePlantOwners           = 48;
export const IdxStatePlants                = 49;

export let keyMap: string[] = [
	sc.ParamActive,
	sc.ParamActiveReason,
	sc.ParamAmount,
	sc.ParamClaimID,
	sc.ParamClaimId,
	sc.ParamClaimed,
	sc.ParamCovered,
	sc.ParamCurrentWater,
	sc.ParamDescription,
	sc.ParamDuration,
	sc.ParamFunds,
	sc.ParamId,
	sc.ParamLattitude,
	sc.ParamLocation,
	sc.ParamLongitude,
	sc.ParamManufacturer,
	sc.ParamName,
	sc.ParamNewPlant,
	sc.ParamNewState,
	sc.ParamOracleId,
	sc.ParamOwner,
	sc.ParamOwnerId,
	sc.ParamPayReward,
	sc.ParamPlantId,
	sc.ParamReqOwnerId,
	sc.ParamReqPlantId,
	sc.ParamReward,
	sc.ParamTimeoutDuration,
	sc.ParamTimestamp,
	sc.ParamTo,
	sc.ParamValue,
	sc.ParamWaterLevel,
	sc.ParamWaterTarget,
	sc.ParamWaterThreshold,
	sc.ResultClaim,
	sc.ResultClaims,
	sc.ResultIsOwner,
	sc.ResultOracles,
	sc.ResultOwner,
	sc.ResultPlant,
	sc.ResultPlants,
	sc.StateAllowedPlantOracles,
	sc.StateAllowedWeatherOracles,
	sc.StateClaimIds,
	sc.StateClaims,
	sc.StateOwnedPlants,
	sc.StateOwner,
	sc.StatePlantIds,
	sc.StatePlantOwners,
	sc.StatePlants,
];

export let idxMap: wasmlib.Key32[] = new Array(keyMap.length);
