// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmtypes from "wasmlib/wasmtypes";
import * as sc from "./index";

export class ArrayOfImmutableHash extends wasmtypes.ScProxy {

	length(): u32 {
		return this.proxy.length();
	}

	getHash(index: u32): wasmtypes.ScImmutableHash {
		return new wasmtypes.ScImmutableHash(this.proxy.index(index));
	}
}

export class ImmutableIds extends ArrayOfImmutableHash {
}

export class ArrayOfMutableHash extends wasmtypes.ScProxy {

	appendHash(): wasmtypes.ScMutableHash {
		return new wasmtypes.ScMutableHash(this.proxy.append());
	}

	clear(): void {
		this.proxy.clearArray();
	}

	length(): u32 {
		return this.proxy.length();
	}

	getHash(index: u32): wasmtypes.ScMutableHash {
		return new wasmtypes.ScMutableHash(this.proxy.index(index));
	}
}

export class MutableIds extends ArrayOfMutableHash {
}

export class ArrayOfImmutablePlant extends wasmtypes.ScProxy {

	length(): u32 {
		return this.proxy.length();
	}

	getPlant(index: u32): sc.ImmutablePlant {
		return new sc.ImmutablePlant(this.proxy.index(index));
	}
}

export class ImmutablePlants extends ArrayOfImmutablePlant {
}

export class ArrayOfMutablePlant extends wasmtypes.ScProxy {

	appendPlant(): sc.MutablePlant {
		return new sc.MutablePlant(this.proxy.append());
	}

	clear(): void {
		this.proxy.clearArray();
	}

	length(): u32 {
		return this.proxy.length();
	}

	getPlant(index: u32): sc.MutablePlant {
		return new sc.MutablePlant(this.proxy.index(index));
	}
}

export class MutablePlants extends ArrayOfMutablePlant {
}
