// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package plantobelly

import (
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib"
)

const (
	IdxParamActive          = 0
	IdxParamActiveReason    = 1
	IdxParamAmount          = 2
	IdxParamClaimID         = 3
	IdxParamClaimId         = 4
	IdxParamClaimed         = 5
	IdxParamCovered         = 6
	IdxParamCurrentWater    = 7
	IdxParamDescription     = 8
	IdxParamDuration        = 9
	IdxParamFunds           = 10
	IdxParamId              = 11
	IdxParamLattitude       = 12
	IdxParamLocation        = 13
	IdxParamLongitude       = 14
	IdxParamManufacturer    = 15
	IdxParamName            = 16
	IdxParamNewPlant        = 17
	IdxParamNewState        = 18
	IdxParamOracleId        = 19
	IdxParamOwner           = 20
	IdxParamOwnerId         = 21
	IdxParamPayReward       = 22
	IdxParamPlantId         = 23
	IdxParamReqOwnerId      = 24
	IdxParamReqPlantId      = 25
	IdxParamReward          = 26
	IdxParamTimeoutDuration = 27
	IdxParamTimestamp       = 28
	IdxParamTo              = 29
	IdxParamValue           = 30
	IdxParamWaterLevel      = 31
	IdxParamWaterTarget     = 32
	IdxParamWaterThreshold  = 33

	IdxResultClaim   = 34
	IdxResultClaims  = 35
	IdxResultIsOwner = 36
	IdxResultOracles = 37
	IdxResultOwner   = 38
	IdxResultPlant   = 39
	IdxResultPlants  = 40

	IdxStateAllowedPlantOracles   = 41
	IdxStateAllowedWeatherOracles = 42
	IdxStateClaimIds              = 43
	IdxStateClaims                = 44
	IdxStateOwnedPlants           = 45
	IdxStateOwner                 = 46
	IdxStatePlantIds              = 47
	IdxStatePlantOwners           = 48
	IdxStatePlants                = 49
)

const keyMapLen = 50

var keyMap = [keyMapLen]wasmlib.Key{
	ParamActive,
	ParamActiveReason,
	ParamAmount,
	ParamClaimID,
	ParamClaimId,
	ParamClaimed,
	ParamCovered,
	ParamCurrentWater,
	ParamDescription,
	ParamDuration,
	ParamFunds,
	ParamId,
	ParamLattitude,
	ParamLocation,
	ParamLongitude,
	ParamManufacturer,
	ParamName,
	ParamNewPlant,
	ParamNewState,
	ParamOracleId,
	ParamOwner,
	ParamOwnerId,
	ParamPayReward,
	ParamPlantId,
	ParamReqOwnerId,
	ParamReqPlantId,
	ParamReward,
	ParamTimeoutDuration,
	ParamTimestamp,
	ParamTo,
	ParamValue,
	ParamWaterLevel,
	ParamWaterTarget,
	ParamWaterThreshold,
	ResultClaim,
	ResultClaims,
	ResultIsOwner,
	ResultOracles,
	ResultOwner,
	ResultPlant,
	ResultPlants,
	StateAllowedPlantOracles,
	StateAllowedWeatherOracles,
	StateClaimIds,
	StateClaims,
	StateOwnedPlants,
	StateOwner,
	StatePlantIds,
	StatePlantOwners,
	StatePlants,
}

var idxMap [keyMapLen]wasmlib.Key32
