// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;

pub const SC_NAME        : &str = "plantobelly";
pub const SC_DESCRIPTION : &str = "plantobelly smart contract responsible for handling plants";
pub const HSC_NAME       : ScHname = ScHname(0x1eaa52f2);

pub const PARAM_ACTIVE           : &str = "active";
pub const PARAM_ACTIVE_REASON    : &str = "activeReason";
pub const PARAM_AMOUNT           : &str = "amount";
pub const PARAM_CLAIMED          : &str = "claimed";
pub const PARAM_COVERED          : &str = "covered";
pub const PARAM_CURRENT_WATER    : &str = "currentWater";
pub const PARAM_DESCRIPTION      : &str = "description";
pub const PARAM_DURATION         : &str = "duration";
pub const PARAM_FUNDS            : &str = "funds";
pub const PARAM_ID               : &str = "id";
pub const PARAM_LATTITUDE        : &str = "lattitude";
pub const PARAM_LOCATION         : &str = "location";
pub const PARAM_LONGITUDE        : &str = "longitude";
pub const PARAM_MANUFACTURER     : &str = "manufacturer";
pub const PARAM_MINT_CLAIM_ID    : &str = "mintClaimId";
pub const PARAM_NAME             : &str = "name";
pub const PARAM_NEW_PLANT        : &str = "newPlant";
pub const PARAM_NEW_STATE        : &str = "newState";
pub const PARAM_ORACLE_ID        : &str = "oracleId";
pub const PARAM_OWNER            : &str = "owner";
pub const PARAM_OWNER_ID         : &str = "ownerId";
pub const PARAM_PAY_REWARD       : &str = "payReward";
pub const PARAM_PLANT_ID         : &str = "plantId";
pub const PARAM_REQ_CLAIM_ID     : &str = "reqClaimId";
pub const PARAM_REQ_OWNER_ID     : &str = "reqOwnerId";
pub const PARAM_REQ_PLANT_ID     : &str = "reqPlantId";
pub const PARAM_REWARD           : &str = "reward";
pub const PARAM_TIMEOUT_DURATION : &str = "timeoutDuration";
pub const PARAM_TIMESTAMP        : &str = "timestamp";
pub const PARAM_TO               : &str = "to";
pub const PARAM_VALUE            : &str = "value";
pub const PARAM_WATER_LEVEL      : &str = "waterLevel";
pub const PARAM_WATER_TARGET     : &str = "waterTarget";
pub const PARAM_WATER_THRESHOLD  : &str = "waterThreshold";

pub const RESULT_CLAIM    : &str = "claim";
pub const RESULT_CLAIMS   : &str = "claims";
pub const RESULT_IS_OWNER : &str = "isOwner";
pub const RESULT_ORACLES  : &str = "oracles";
pub const RESULT_OWNER    : &str = "owner";
pub const RESULT_PLANT    : &str = "plant";
pub const RESULT_PLANTS   : &str = "plants";

pub const STATE_ALLOWED_PLANT_ORACLES   : &str = "allowedPlantOracles";
pub const STATE_ALLOWED_WEATHER_ORACLES : &str = "allowedWeatherOracles";
pub const STATE_CLAIM_IDS               : &str = "claimIds";
pub const STATE_CLAIMS                  : &str = "claims";
pub const STATE_OWNED_PLANTS            : &str = "ownedPlants";
pub const STATE_OWNER                   : &str = "owner";
pub const STATE_PLANT_IDS               : &str = "plantIds";
pub const STATE_PLANT_OWNERS            : &str = "plantOwners";
pub const STATE_PLANTS                  : &str = "plants";

pub const FUNC_ACTIVATE_PLANT_OWNER      : &str = "activatePlantOwner";
pub const FUNC_ADD_PLANT_FUNDS           : &str = "addPlantFunds";
pub const FUNC_ADD_PLANT_ORACLE          : &str = "addPlantOracle";
pub const FUNC_ADD_WEATHER_ORACLE        : &str = "addWeatherOracle";
pub const FUNC_CLAIM_WATERING            : &str = "claimWatering";
pub const FUNC_EDIT_OWN_PLANT            : &str = "editOwnPlant";
pub const FUNC_INIT                      : &str = "init";
pub const FUNC_INTERRUPT_WEATHER_EVENT   : &str = "interruptWeatherEvent";
pub const FUNC_MINT_PLANT                : &str = "mintPlant";
pub const FUNC_MINT_PLANT_RAW            : &str = "mintPlantRaw";
pub const FUNC_PAY_CLAIMER               : &str = "payClaimer";
pub const FUNC_RESOLVE_CLAIM             : &str = "resolveClaim";
pub const FUNC_SET_OWNER                 : &str = "setOwner";
pub const FUNC_SET_PLANT_WATER           : &str = "setPlantWater";
pub const FUNC_SET_PLANT_WEATHER_TIMEOUT : &str = "setPlantWeatherTimeout";
pub const VIEW_GET_CLAIM                 : &str = "getClaim";
pub const VIEW_GET_CLAIMS                : &str = "getClaims";
pub const VIEW_GET_OWNER                 : &str = "getOwner";
pub const VIEW_GET_PLANT                 : &str = "getPlant";
pub const VIEW_GET_PLANT_ORACLES         : &str = "getPlantOracles";
pub const VIEW_GET_PLANTS                : &str = "getPlants";
pub const VIEW_GET_PLANTS_FROM_OWNER     : &str = "getPlantsFromOwner";
pub const VIEW_GET_WEATHER_ORACLES       : &str = "getWeatherOracles";
pub const VIEW_IS_PLANT_OWNER            : &str = "isPlantOwner";

pub const HFUNC_ACTIVATE_PLANT_OWNER      : ScHname = ScHname(0x666005c8);
pub const HFUNC_ADD_PLANT_FUNDS           : ScHname = ScHname(0xe756567a);
pub const HFUNC_ADD_PLANT_ORACLE          : ScHname = ScHname(0xca04a73a);
pub const HFUNC_ADD_WEATHER_ORACLE        : ScHname = ScHname(0x5f3b8b83);
pub const HFUNC_CLAIM_WATERING            : ScHname = ScHname(0x1c41f3ed);
pub const HFUNC_EDIT_OWN_PLANT            : ScHname = ScHname(0xebba038d);
pub const HFUNC_INIT                      : ScHname = ScHname(0x1f44d644);
pub const HFUNC_INTERRUPT_WEATHER_EVENT   : ScHname = ScHname(0xc42865d1);
pub const HFUNC_MINT_PLANT                : ScHname = ScHname(0x6aeb84a1);
pub const HFUNC_MINT_PLANT_RAW            : ScHname = ScHname(0x7b8d3bec);
pub const HFUNC_PAY_CLAIMER               : ScHname = ScHname(0x2c37ad88);
pub const HFUNC_RESOLVE_CLAIM             : ScHname = ScHname(0x302e03fa);
pub const HFUNC_SET_OWNER                 : ScHname = ScHname(0x2a15fe7b);
pub const HFUNC_SET_PLANT_WATER           : ScHname = ScHname(0x6a4d53e6);
pub const HFUNC_SET_PLANT_WEATHER_TIMEOUT : ScHname = ScHname(0x6f912118);
pub const HVIEW_GET_CLAIM                 : ScHname = ScHname(0x80ab4e34);
pub const HVIEW_GET_CLAIMS                : ScHname = ScHname(0xb307c3ab);
pub const HVIEW_GET_OWNER                 : ScHname = ScHname(0x137107a6);
pub const HVIEW_GET_PLANT                 : ScHname = ScHname(0x356278e0);
pub const HVIEW_GET_PLANT_ORACLES         : ScHname = ScHname(0xf1939bee);
pub const HVIEW_GET_PLANTS                : ScHname = ScHname(0x39ab8724);
pub const HVIEW_GET_PLANTS_FROM_OWNER     : ScHname = ScHname(0x1e36cb62);
pub const HVIEW_GET_WEATHER_ORACLES       : ScHname = ScHname(0x66e143a7);
pub const HVIEW_IS_PLANT_OWNER            : ScHname = ScHname(0x84c4d3ec);
